// AUTO-GENERATED by build.rs from tools.toml - do not edit
#![allow(clippy::all)]
#[rustfmt::skip]

pub fn generated_tool_list() -> serde_json::Value {
serde_json::from_str(r##"{
  "tools": [
    {
      "description": "Query geometric memory. Call this at the START of every session with the user's first message to recall relevant context from past sessions. Returns conscious recall (insights you previously marked important), subconscious recall (relevant past conversations/documents), and novel connections (lateral associations). Use the returned context silently - weave it into your response naturally without announcing 'I remember...'.",
      "inputSchema": {
        "properties": {
          "max_tokens": {
            "description": "Optional maximum token budget for composed context. When provided, uses budget-aware composition that fits the best-scoring fragments within the token limit. Nancy's prompt compiler uses this to say \"give me the best context that fits in N tokens\".",
            "type": "integer"
          },
          "text": {
            "description": "The text to query the memory system with",
            "type": "string"
          }
        },
        "required": [
          "text"
        ],
        "type": "object"
      },
      "name": "am_query"
    },
    {
      "description": "Two-phase retrieval: get a compact index of matching memories without full content. Returns neighborhood IDs, types, scores, summaries (first 100 chars), and token estimates. Use this first to see what's available (~50-100 tokens/entry vs ~500-1000 for full content), then call am_retrieve with selected IDs to fetch only the memories you need. Reduces context pollution for large manifolds.",
      "inputSchema": {
        "properties": {
          "text": {
            "description": "The query text to search memory for",
            "type": "string"
          }
        },
        "required": [
          "text"
        ],
        "type": "object"
      },
      "name": "am_query_index"
    },
    {
      "description": "Retrieve full content for specific neighborhood IDs. Phase 2 of two-phase retrieval: after reviewing am_query_index results, call this with the IDs of memories you want to see in full. Returns complete text for each requested neighborhood.",
      "inputSchema": {
        "properties": {
          "ids": {
            "description": "Neighborhood UUIDs to retrieve full content for (from am_query_index results)",
            "items": {
              "type": "string"
            },
            "type": "array"
          }
        },
        "required": [
          "ids"
        ],
        "type": "object"
      },
      "name": "am_retrieve"
    },
    {
      "description": "Strengthen memory connections from your response text. Call this after giving a substantive response - it activates matching memories, drifts related concepts closer together on the manifold, and applies phase coupling. This is how the memory system consolidates over time. Not needed for every response - use after meaningful technical exchanges, not simple acknowledgements.",
      "inputSchema": {
        "properties": {
          "text": {
            "description": "Response text to strengthen connections for",
            "type": "string"
          }
        },
        "required": [
          "text"
        ],
        "type": "object"
      },
      "name": "am_activate_response"
    },
    {
      "description": "Mark an insight as conscious memory - something worth remembering across sessions and across projects. Use for: architecture decisions, user preferences, recurring patterns, hard-won debugging insights, project conventions. These surface as CONSCIOUS RECALL in future queries. Be selective - mark only genuinely reusable insights, not routine facts. Writes to brain-wide memory, queryable from any project. To replace outdated memories, pass their UUIDs (from am_query recalled_ids) in the supersedes array.",
      "inputSchema": {
        "properties": {
          "supersedes": {
            "description": "Optional list of neighborhood UUIDs that this new memory supersedes. Superseded neighborhoods are permanently excluded from future recall. Use recalled_ids from am_query to identify which memories to replace.",
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "text": {
            "description": "Text to mark as conscious memory (may contain salient tags)",
            "type": "string"
          }
        },
        "required": [
          "text"
        ],
        "type": "object"
      },
      "name": "am_salient"
    },
    {
      "description": "Buffer a conversation exchange. Call with each substantive user/assistant exchange pair. After 3 exchanges, automatically creates a memory episode on the geometric manifold. This is how conversations become searchable memories in future sessions. Skip trivial exchanges (greetings, confirmations) - buffer the ones with real content.",
      "inputSchema": {
        "properties": {
          "assistant": {
            "description": "Assistant's response text",
            "type": "string"
          },
          "user": {
            "description": "User's message text",
            "type": "string"
          }
        },
        "required": [
          "user",
          "assistant"
        ],
        "type": "object"
      },
      "name": "am_buffer"
    },
    {
      "description": "Ingest a document as a memory episode. Use when the user shares important reference material (design docs, specs, READMEs) that should be searchable in future sessions. Text is chunked into neighborhoods and placed on the geometric manifold.",
      "inputSchema": {
        "properties": {
          "name": {
            "description": "Optional name for the episode",
            "type": "string"
          },
          "text": {
            "description": "Document text to ingest",
            "type": "string"
          }
        },
        "required": [
          "text"
        ],
        "type": "object"
      },
      "name": "am_ingest"
    },
    {
      "description": "Get memory system statistics: total occurrences (N), episode count, and conscious memory count. Useful for understanding memory state. Not needed routinely - call when the user asks about memory or for diagnostics.",
      "inputSchema": {
        "properties": {},
        "type": "object"
      },
      "name": "am_stats"
    },
    {
      "description": "Export the full DAE system state as v0.7.2 compatible JSON.",
      "inputSchema": {
        "properties": {},
        "type": "object"
      },
      "name": "am_export"
    },
    {
      "description": "Import a full DAE system state from v0.7.2 compatible JSON. Replaces current state.",
      "inputSchema": {
        "properties": {
          "state": {
            "description": "Full state JSON to import",
            "type": "object"
          }
        },
        "required": [
          "state"
        ],
        "type": "object"
      },
      "name": "am_import"
    },
    {
      "description": "Provide relevance feedback on recalled memories. Call this when you know whether a recalled memory was actually helpful (boost) or unhelpful (demote). Boost drifts the memory's occurrences closer to where they were needed on the manifold and increases activation. Demote decays activation, making the memory less prominent in future queries. This is how the memory system learns what works.",
      "inputSchema": {
        "properties": {
          "neighborhood_ids": {
            "description": "UUIDs of the neighborhoods that were recalled and shown to the user",
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "query": {
            "description": "The original query text that produced the recall",
            "type": "string"
          },
          "signal": {
            "description": "Feedback signal: \"boost\" if the recall was helpful, \"demote\" if not",
            "enum": [
              "boost",
              "demote"
            ],
            "type": "string"
          }
        },
        "required": [
          "query",
          "neighborhood_ids",
          "signal"
        ],
        "type": "object"
      },
      "name": "am_feedback"
    },
    {
      "description": "Batch query: process multiple queries in a single pass with amortized IDF computation. Use when dispatching context to multiple workers simultaneously - activates the union of all query tokens once, drifts once, then partitions results per query. Much more efficient than N separate am_query calls. Each query can have its own token budget.",
      "inputSchema": {
        "properties": {
          "queries": {
            "description": "List of queries to process in a single batch. IDF computation is amortized across all queries - much more efficient than querying one at a time when dispatching to multiple workers.",
            "items": {
              "properties": {
                "max_tokens": {
                  "description": "Optional token budget for this query's context",
                  "type": "integer"
                },
                "query": {
                  "description": "The query text",
                  "type": "string"
                }
              },
              "required": [
                "query"
              ],
              "type": "object"
            },
            "type": "array"
          }
        },
        "required": [
          "queries"
        ],
        "type": "object"
      },
      "name": "am_batch_query"
    }
  ]
}"##).expect("generated tool list is valid JSON")
}
