// AUTO-GENERATED by build.rs from tools.toml - do not edit
#![allow(dead_code, unused)]
#![allow(clippy::all)]
#[rustfmt::skip]
pub const QUERY_ABOUT: &str = "Query geometric memory for relevant context.";
#[rustfmt::skip]
pub const QUERY_TEXT_HELP: &str = "Query text";
#[rustfmt::skip]
pub const QUERY_MAX_TOKENS_HELP: &str = "Maximum token budget for composed context";

#[rustfmt::skip]
pub const QUERY_INDEX_ABOUT: &str = "Get a compact index of matching memories (two-phase retrieval step 1).";
#[rustfmt::skip]
pub const QUERY_INDEX_TEXT_HELP: &str = "Query text";

#[rustfmt::skip]
pub const RETRIEVE_ABOUT: &str = "Retrieve full content for specific neighborhood IDs (two-phase retrieval step 2).";
#[rustfmt::skip]
pub const RETRIEVE_IDS_HELP: &str = "Neighborhood UUIDs to retrieve";

#[rustfmt::skip]
pub const ACTIVATE_RESPONSE_ABOUT: &str = "Strengthen memory connections from response text.";
#[rustfmt::skip]
pub const ACTIVATE_RESPONSE_TEXT_HELP: &str = "Response text";

#[rustfmt::skip]
pub const SALIENT_ABOUT: &str = "Mark an insight as conscious (cross-session) memory.";
#[rustfmt::skip]
pub const SALIENT_TEXT_HELP: &str = "Text to mark as conscious memory";
#[rustfmt::skip]
pub const SALIENT_SUPERSEDES_HELP: &str = "Neighborhood UUIDs this memory supersedes";

#[rustfmt::skip]
pub const BUFFER_ABOUT: &str = "Buffer a conversation exchange pair.";
#[rustfmt::skip]
pub const BUFFER_USER_HELP: &str = "User's message text";
#[rustfmt::skip]
pub const BUFFER_ASSISTANT_HELP: &str = "Assistant's response text";

#[rustfmt::skip]
pub const INGEST_ABOUT: &str = "Ingest a document as a memory episode.";
#[rustfmt::skip]
pub const INGEST_TEXT_HELP: &str = "Document text to ingest";
#[rustfmt::skip]
pub const INGEST_NAME_HELP: &str = "Episode name";

#[rustfmt::skip]
pub const STATS_ABOUT: &str = "Get memory system statistics.";

#[rustfmt::skip]
pub const EXPORT_ABOUT: &str = "Export the full DAE system state as JSON.";

#[rustfmt::skip]
pub const IMPORT_ABOUT: &str = "Import a full DAE system state from JSON.";
#[rustfmt::skip]
pub const IMPORT_STATE_HELP: &str = "Full state JSON to import";

#[rustfmt::skip]
pub const FEEDBACK_ABOUT: &str = "Provide relevance feedback on recalled memories.";
#[rustfmt::skip]
pub const FEEDBACK_QUERY_HELP: &str = "Original query text";
#[rustfmt::skip]
pub const FEEDBACK_NEIGHBORHOOD_IDS_HELP: &str = "Neighborhood UUIDs to provide feedback on";
#[rustfmt::skip]
pub const FEEDBACK_SIGNAL_HELP: &str = "Feedback signal: boost or demote";

#[rustfmt::skip]
pub const BATCH_QUERY_ABOUT: &str = "Process multiple queries in a single batch pass.";
#[rustfmt::skip]
pub const BATCH_QUERY_QUERIES_HELP: &str = "List of queries (JSON array of {query, max_tokens?} objects)";
